#!/bin/bash
#SBATCH --time=20:59:00
#SBATCH --nodes=1
#SBATCH --ntasks=2
#SBATCH --cpus-per-task=4
#SBATCH --job-name=classif_sequence_RNN
#SBATCH --mem=1000
#SBATCH --mail-type=END
#SBATCH --mail-user=a.r.pratama@rug.nl
module load Python/3.5.1-foss-2016a
